menv: clean
	cc -Wall -Wextra -Werror ft_env.c ../parsing/libft/*.c

mecho: clean
	cc -Wall -Wextra -Werror ft_echo.c ft_unset.c ../parsing/garbage_collector.c ../parsing/libft/*.c

mpwd: clean
	cc -Wall -Wextra -Werror ft_pwd.c ../parsing/libft/*.c

mexit: clean
	cc -Wall -Wextra -Werror ft_exit.c ft_unset.c ../parsing/garbage_collector.c ../parsing/helpers.c ../parsing/libft/*.c

munset: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

mexport: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

clean:
	rm -f a.out