menv: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

mecho: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

mpwd: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

mexit: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

munset: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

mexport: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

mcd: clean
	cc -Wall -Wextra -Werror *.c ../parsing/*.c ../parsing/libft/*.c

clean:
	rm -f a.out